/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IOCalVistes;

import IOCaldades.CodiAccess;
import IOCaltasques.JsonParse;
import IOCaldades.DadesAcces;
import IOCaltasques.Registre;
import IOCaldades.OperacionsServidor;
import IOCaltasques.Administracio;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Xavi
 */
public class PantallaLogin extends javax.swing.JFrame {

    private String codi;
    private CodiAccess codiAccess;

    /**
     * Crea nou formulari de Login
     */
    public PantallaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelusuari = new javax.swing.JLabel();
        JLabelcontrasenya = new javax.swing.JLabel();
        introduirUsuari = new javax.swing.JTextField();
        introduirContrasenya = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        Tancar = new javax.swing.JButton();
        Titol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Botigapp");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        JLabelusuari.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        JLabelusuari.setText("Usuari");
        getContentPane().add(JLabelusuari);
        JLabelusuari.setBounds(130, 190, 130, 15);

        JLabelcontrasenya.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        JLabelcontrasenya.setText("Contrasenya");
        getContentPane().add(JLabelcontrasenya);
        JLabelcontrasenya.setBounds(130, 220, 80, 15);

        introduirUsuari.setToolTipText("Nom d'usuari");
        getContentPane().add(introduirUsuari);
        introduirUsuari.setBounds(230, 190, 210, 20);

        introduirContrasenya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                introduirContrasenyaMouseClicked(evt);
            }
        });
        getContentPane().add(introduirContrasenya);
        introduirContrasenya.setBounds(230, 220, 210, 20);

        jLabel1.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        jLabel1.setText("Introdueix el nom d'usuari i la contrasenya");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 140, 240, 30);

        entrar.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(350, 260, 90, 23);

        registrar.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        registrar.setText("Registrarse");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar);
        registrar.setBounds(230, 260, 110, 23);

        Tancar.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        Tancar.setText("Tancar");
        Tancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TancarActionPerformed(evt);
            }
        });
        getContentPane().add(Tancar);
        Tancar.setBounds(620, 490, 100, 23);

        Titol.setFont(new java.awt.Font("Decker", 1, 36)); // NOI18N
        Titol.setText("Botigapp Comerç Local");
        getContentPane().add(Titol);
        Titol.setBounds(220, 40, 430, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        String usuari = introduirUsuari.getText();
        String contrasenya = String.valueOf(introduirContrasenya.getPassword());
        DadesAcces dadesAcces = new DadesAcces(usuari, contrasenya);
        OperacionsServidor dades = new OperacionsServidor();
        
        try {
            codi = dades.login(dadesAcces);
            JsonParse jsonParse = new JsonParse();
            if (jsonParse.isJSONValid(codi)) {
                JSONObject object = new JSONObject(codi);
                String missatge = object.getString("message");
                JOptionPane.showMessageDialog(null, missatge);
            } else {
                PantallaLogin.super.dispose();
                Administracio administracio = new Administracio(codi);
                administracio.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(PantallaLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(PantallaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_entrarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        Registre registre = new Registre();
        PantallaLogin.super.dispose();
        registre.setVisible(true);

    }//GEN-LAST:event_registrarActionPerformed

    private void TancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TancarActionPerformed
        PantallaLogin.super.dispose();
    }//GEN-LAST:event_TancarActionPerformed

    private void introduirContrasenyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_introduirContrasenyaMouseClicked
        introduirContrasenya.setText("");
    }//GEN-LAST:event_introduirContrasenyaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelcontrasenya;
    private javax.swing.JLabel JLabelusuari;
    private javax.swing.JButton Tancar;
    private javax.swing.JLabel Titol;
    private javax.swing.JButton entrar;
    private javax.swing.JPasswordField introduirContrasenya;
    private javax.swing.JTextField introduirUsuari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

}
